apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-rust
  namespace: rust
spec:
  concurrencyPolicy: Forbid
  schedule: '0 */12 * * *' # Run every 12 hours
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: rust-svc
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/rust'
