apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rust-svc
  namespace: rust
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["rust"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rust-svc
  namespace: rust
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rust-svc
subjects:
  - kind: ServiceAccount
    name: rust-svc
    namespace: rust
