apiVersion: v1
kind: Secret
metadata:
  name: ssh-sec
  namespace: rust
  labels:
    app: rust
type: Opaque
data:
  USER_NAME: <YOUR SSH USER>
  USER_PASSWORD: <Base64 Encoded Password>
---
apiVersion: v1
kind: Secret
metadata:
  name: rust-rcon-pass
  namespace: rust
  labels:
    app: rust
type: Opaque
data:
  USER_PASSWORD: <Base64 Encoded Password for RCON>
