apiVersion: v1
kind: Service
metadata:
  labels:
    app: rust
  name: rust-udp
  namespace: rust
  annotations:
    metallb.universe.tf/allow-shared-ip: "YOURIP"
spec:
  ports:
    - name: steam
      port: 28015
      protocol: UDP
      targetPort: 28015
  selector:
    app: rust
  type: LoadBalancer
  loadBalancerIP: YOURIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rust
  name: rust-tcp
  namespace: rust
  annotations:
    metallb.universe.tf/allow-shared-ip: "YOURIP"
spec:
  ports:
    - name: ssh
      port: 2222
    - name: rcon
      port: 28016
      protocol: TCP
      targetPort: 28016
    - name: rustplus
      port: 28083
      protocol: TCP
      targetPort: 28083
  selector:
    app: rust
  type: LoadBalancer
  loadBalancerIP: YOURIP
